services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_MASTER_JDBC_URL=jdbc:mysql://${DB_MASTER_HOST}:${DB_MASTER_PORT}/flavortales
      - SPRING_DATASOURCE_MASTER_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_MASTER_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_SLAVE_JDBC_URL=jdbc:mysql://${DB_SLAVE_HOST}:${DB_SLAVE_PORT}/flavortales
      - SPRING_DATASOURCE_SLAVE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_SLAVE_PASSWORD=${DB_PASSWORD}
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend