spring:
  config:
    import:
      - classpath:database-dev.yml
      - classpath:mail.yml
      - classpath:security.yml
      - classpath:redis.yml
      - classpath:poi.yml
      - classpath:r2.yml
      - classpath:audio.yml
      - optional:classpath:mongodb.yml
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/flavortales}
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
