spring:
  config:
    import:
      - classpath:database-dev.yml
      - classpath:mail.yml
      - classpath:security.yml
      - classpath:redis.yml
      - classpath:poi.yml
      - classpath:r2.yml
      - classpath:audio.yml
      - classpath:mongodb.yml
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
