spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:noop@localhost}
    password: ${SPRING_MAIL_PASSWORD:noop}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  verification:
    expiration-minutes: 15
  mail:
    from: ${SPRING_MAIL_USERNAME:noop@localhost}
    from-name: FlavorTales
    admin-email: ${SPRING_MAIL_USERNAME:noop@localhost}
    support-email: ${SPRING_MAIL_USERNAME:noop@localhost}
    company-name: FlavorTales
