
spring:
  datasource:
    url: jdbc:mysql://33bxd8.h.filess.io:3307/FlavorTales_severalgas
    username: FlavorTales_severalgas
    password: c85f690194ff438b418499f3f43712cab3185c1b
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: FlavorTalesHikariPool
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://FlavorTalesMongoDB_hurriedtop:de6b3717a8c40470731d1a4e26bd7c702888970d@4465og.h.filess.io:27018/FlavorTalesMongoDB_hurriedtop
